# Generated by Django 4.2 on 2023-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
