# Generated by Django 4.2 on 2023-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultes', '0003_alter_faculty_icon_alter_faculty_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
