# Generated by Django 4.2 on 2023-04-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainImage',
        ),
    ]
