# Generated by Django 4.2 on 2023-04-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='groups',
            new_name='group',
        ),
    ]
